

trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'    
    

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Job is building!! 
- stage: DevDeploy
  jobs:
    - deployment: DevDeployJob
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo DevDeploy Success!!
- stage: QADeploy
  jobs:
    - deployment: QADeployJob
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo QADeploy Success!!
    